### ISSUE TITLE
Éles rendszerben OPERATION_FAILED

### ISSUE THREAD

**Issue by tothj74** [nav-gov-hu/eVAT#100]
Az éles rendszer felé küldütt manageDeclarationUploadRequest-re ezt a választ kapom:
<result>
<funcCode>ERROR</funcCode>
<errorCode>OPERATION_FAILED</errorCode>
<message>Technikai hiba! Kérjük, próbálkozzon később!</message>
</result>

**Comment by tothj74** [comment]
Most a tesztrendszeren is.

**Comment by renced42** [comment]
Kedves @tothj74 

Nem tudom pontosan mikor volt a hiba de lehet, hogy éppen verzióváltás volt, még mindig áll a probléma?

**Comment by tothj74** [comment]
Kedves @renced42 
Jelenleg az alábbiakat tapasztalom:
tesztrendszeren a ManageDeclarationUpload request felmegy, a partíció feltöltés viszont mintha timeout-olna, és  a responseBody:
ERROR
OPERATION_FAILED
Technikai hiba! Kérjük, próbálkozzon később!

Az éles rendszerben érthetetlen módon INVALID_SECURITY_USER választ kapok egy olyan technikai felhasználóra, akire minden eÁfa jogosultság be lett állítva és az OSA-beli lekérdezések rendben lefutnak, tehát a jelszó, aláírókulcs is rendben van. 
Milyen adat szükséges a jelenség kibogozásához?
A hash képzés jó kell legyen, különben tesztrendszerben se tudnék sikeresen küldeni requestet.

**Comment by tothj74** [comment]
Kedves @renced42 
Most működik, zárom.
