### ISSUE TITLE
éles rendszer beküldés

### ISSUE THREAD

**Issue by laszlo90** [nav-gov-hu/eVAT#101]
éles rendszerben beküldéskor ezt a választ kapjuk: Az analitika státusza nem felel meg a beadáshoz szükséges státusznak! (INVALID_STATUS)
teszt rendszerben finished státusz érkezik vissza, mi lehet a hiba?

**Comment by renced42** [comment]
Kedves @laszlo90 
Kérlek nézd meg, hogy a hiba fenn áll-e.
