### ISSUE TITLE
INVALID_XML_SCHEMA: detailedAddress

### ISSUE THREAD

**Issue by laszlo90** [nav-gov-hu/eVAT#102]
ez a hibaüzenet jön az éles rendszerben.

így adjuk meg az adatokat:
<n0:partnerInfo>
				<n0:partnerStatus>OTHER</n0:partnerStatus>
				<n0:partnerTaxData>
					<n0:communityVatNumber>CZ11111111</n0:communityVatNumber>
				</n0:partnerTaxData>
				<n0:partnerName>Teszt Partner 1</n0:partnerName>
				<n0:partnerAddress>
					<osabase:simpleAddress>
						<osabase:countryCode>CZ</osabase:countryCode>
						<osabase:postalCode>61600</osabase:postalCode>
						<osabase:city>Teszt Város 1</osabase:city>
						<osabase:additionalAddressDetail>Teszt utca 1</osabase:additionalAddressDetail>
					</osabase:simpleAddress>
				</n0:partnerAddress>
			</n0:partnerInfo>

hiba:
<technicalValidationMessages>
<validationResultCode>ERROR</validationResultCode>
<validationErrorCode>INVALID_XML_SCHEMA</validationErrorCode>
<message>
Invalid XML séma! cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/base":simpleAddress}'. One of '{"http://schemas.nav.gov.hu/EAR/1.0/base":simpleAddress, "http://schemas.nav.gov.hu/EAR/1.0/base":detailedAddress}' is expected.
</message>
</technicalValidationMessages>

**Comment by renced42** [comment]
Kedves @laszlo90 

Az XSD sémában változás volt. Múlt héten publikáltuk a repoban, illetve mai napon kitettük a friss leírást is.
#103
