### ISSUE TITLE
manageDeclarationSubmission

### ISSUE THREAD

**Issue by laszlo90** [nav-gov-hu/eVAT#104]
manageDeclarationSubmission beküldjük a bevallást, meg is jön a bevfeldData és a declarationSummary rész az éles rendszerben, azonban a queryDeclarationProcessingStatus részben finished marad a státusz, mennyi idő kellene, hogy feldolgozódjon, vagy kihagyunk valamit?

**Comment by zbenko** [comment]
A teszt rendszerben nálam ez akkor fordult elő, amikor az adott időszakra már volt submitted státuszú bevallás és növelt verziószámmal próbáltam új bevallást véglegesíteni. Hibaüzenet nélkül végigment a request, de finished állapotban maradt. Ha QueryDeclarationListRequest-el kikérem az adott időszak összes benyújtott bevallását, a response-ban visszakapott összes declarationProcessingId -n végigiterálva megkaptam, hogy melyik declarationProcessingId lett submitted.
Ha nem erről az esetről van szó, akkor nincs ötletem.

**Comment by renced42** [comment]
Kedves @laszlo90 

Kérlek küldj egy request ID-t.

**Comment by renced42** [comment]
Kedves @laszlo90 

Kérlek nézd meg, hogy a hiba fenn áll-e.

**Comment by laszlo90** [comment]
tökéletesen működik, rengeteg bevallást beküldtünk már élesben :)

**Comment by renced42** [comment]
Kedves @renced42 

Köszönöm szépen!
