### ISSUE TITLE
OPERATION_FAILED  ManageDeclarationPartitionRequest esetén a teszt rendszerben

### ISSUE THREAD

**Issue by jsz66** [nav-gov-hu/eVAT#105]
Napok óta ERROR OPERATION_FAILED
Technikai hiba! Kérjük, próbálkozzon később!

ManageDeclarationPartitionRequest esetén a teszt rendszerben ezt az üzenetet kapom. Érdekes, ha változtatás nélkül küldöm, akkor helyesen visszajelzi, hogy a kérés azonosítója már létezik. Ha szándékosan elrontom a feltöltési azonosítót, akkor azt is helyesen jelzi, hogy nem létezik. Ezek szerint a kérés elmegy, és helyes adatok megadásával hosszú idő után kapom az OPERATION_FAILED üzenetet.

**Comment by renced42** [comment]
Kedves @jsz66 

RequestID-t küldj be kérlek meg időpontot.

Köszönöm szépen!

**Comment by jsz66** [comment]
Most ránéztem és a hiba már nem jelentkezik. Köszönöm!
