### ISSUE TITLE
GeneralExceptionResponse XML header nélkül

### ISSUE THREAD

**Issue by migpeti** [nav-gov-hu/eVAT#106]
A GeneralExceptionResponse válasz a  szervertől XML header (<?xml .....) nélkül jön.
Hibakezelő rendszerünk az XML fejlécet figyeli, ha az nincs, akkor html válaszra számít, de ez nem az.

A kérésben a hibás adat:
`<timestamp>2024-02-12T09:46:31</timestamp>`

A formátum javítása után a kérésben:
`<timestamp>2024-02-12T10:09:13.830Z</timestamp>`
már rendben van.

**Comment by renced42** [comment]
Kedves @migpeti 

Gyakorlatilag a jelzett hiba nem lehetséges. Fizikailag nem tudunk ilyent készíteni.
De ennyi infóból nehéz is megmondani, hogy mi a helyzet. Ha küldesz requestID-t akkor rá tudunk nézni.

**Comment by migpeti** [comment]
Köszönöm! 
Sok időt ne szánjatok rá! :-)

Két requestid
315948119A1958270F46E98F092FA6
315949E72FBA2C76F14ED1923D534C
