### ISSUE TITLE
TAXPOINTDATE_LATE WARN időszakhoz tartozó tétel esetén

### ISSUE THREAD

**Issue by tothj74** [nav-gov-hu/eVAT#107]
Az éles rendszerre 2024 januári bevallásra válaszul ez a WARN érkezett:
TAXPOINTDATE_LATE
A levonásba helyezett bizonylat adózási dátuma (teljesítési dátuma) a vonatkozási időszakot (bevallási időszakot) követő dátum.
Tag: VatDeclarationData/vatAnalytics/VatAnalyticsItem/taxpointDate
Value: 2024-01-31

Csak a levonható oldalon szereplő tételekre igaz ez, a fizetendő oldalon nem érkezik erre a dátumra figyelmeztetés.
A bevallási időszak utolsó napjára levonható oldalon ezek szerint már WARN üzenet érkezik?

**Comment by renced42** [comment]
Kedves @tothj74 

Köszi a jelzést nézzük. Ez nem biztos, hogy így jó. Már csak azért sem mert a 2024.01.31 az még a bevallási időszak része.

**Comment by tothj74** [comment]
Kedves @renced42 

Ellenőriztem természetesen. Arra gyanakszom, hogy ez a cég pénzforgalmi elszámolású, nem lehet, hogy ez okozza a zavart?
Ma az m2m helpdeskre beküldtem a dataXML-t egy rejtélyes OPERATION_ABORTED üzenet miatt, ha szeretnéd, egyeztessünk.

**Comment by tothj74** [comment]
> Nem OPERATION_FAILED véletlenül?

Pontosan.
Az issue rögzítésekor csak Warn-ok jöttek. 
Most ugyanazokra az adatokra jön az Aborted státusz és az Operation failed error.

**Comment by u319169** [comment]
Tisztelt tothj74!
Az a kérdésem, hogy fennáll még a probléma? Lévén eléggé régi a bejegyzés.
Üdvözlettel: u319169

**Comment by tothj74** [comment]
Tisztelt @u319169!
Üzleti elemzőink ellenőrizték és már nem tapasztalták a jelzett hibát. 
Zártam az issue-t. 
Köszönettel:  tothj74
