### ISSUE TITLE
403 response

### ISSUE THREAD

**Issue by ppsofthu** [nav-gov-hu/eVAT#109]
Üdvözletem.   Az online számla és a pénztárgép gépi interfész megvalósítása után, úgy gondoltam az e-VAT is problémamentes lesz.   Azonban egy olyan problémába futottam, amire nem tudom merre keressem a megoldását.    Saját teszt és éle userrel, illetve egyik ügyfelem éles userével is **403** hibát kapok.   Úgy gondolom a kommunikáció formája és iránya jó, mert pl. helytelen userrel jön az autentikációs figyelmeztetés,  ha leveszem a jogot az usertől jön a FORBIDDEN.  Viszont ha beállítom neki az e-Vat jogot akkor pl. queryTaxCodeCatalognál is 403.  Milyen lépésekkel lehet behatárolni a probléma okát?

**Comment by renced42** [comment]
Kedves @ppsofthu 

Ha valami adatot megadnál az sokat segítene pl requestID, időpont.

Köszönöm szépen!

**Comment by ppsofthu** [comment]
Köszönöm a gyors reakciót. RequestID : 2dZ+KeQ_vUCM9QeUp75byA

**Comment by ppsofthu** [comment]
Timestamp:2024-02-14T08:18:11.361Z

**Comment by ppsofthu** [comment]
API-TEST Swagger alól sem működik, FORBIDDEN?!  request-ID : Rn8uTSD8AkqhNogbglSFVg

**Comment by ppsofthu** [comment]
Köszönöm a gyors reakciót. RequestID : 2dZ+KeQ_vUCM9QeUp75byA

 

API-TEST Swagger alól sem működik, FORBIDDEN?! request-ID : Rn8uTSD8AkqhNogbglSFVg

 

Közönettl, Rónaszegi Géza

**Comment by nalatreb** [comment]
Sziasztok!

Hasonló problémába ütköztem én is a queryTaxCodeCatalog végpontnál. Teszt és éles rendszeres technikai felhasználó is FORBIDDEN-t kap, hiába van megadva  az eVat jog.
Mi lett itt a probléma megoldása?

Itt vannak az én adataim:
RequestID: xkbfTR7RukSQd7D9_c5GgQ384_0338
Timestamp: 2024-02-20T08:35:52.123Z

**Comment by nalatreb** [comment]
Megtaláltam közben a megoldást: https://github.com/nav-gov-hu/eVAT/issues/90#issuecomment-1896480193
Ha esetleg még ez nem oldódott volna meg.

**Comment by ppsofthu** [comment]
Sajnos az én problémámat nem oldja meg. Nekem nem jelennek meg a másodlagos felhasználók az e-ÁFA ban a megjelölt helyen.    Az e-ÁFA interfész elérés be van jelölve az onlineszámlában.

**Comment by ppsofthu** [comment]
Egy lépéssel előrébb. Hozzáadtam egy új technikai felhasználót. Most már megjelent a technikai felhasználó fül a két felhaználóval.   Innentől más a hibaüzenet legalább...

**Comment by ppsofthu** [comment]
Most már csak a queryTaxCodeCatalog ad hibát, OPERATION_FAILED.   RqID:IyOwfMNLyESBj+DoMuAbTg

**Comment by nalatreb** [comment]
Nálam is az OPERATION_FAILED van most :D

requestId: gCBbPNy_G0msRiucjW7doA0_248227
timestamp: 2024-02-20T09:13:45.123Z

**Comment by ppsofthu** [comment]
Megjavult, zárható, közönöm.
