### ISSUE TITLE
INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by jsz66** [nav-gov-hu/eVAT#112]
Teszt és éles rendszerben is érvénytelen kérés aláírás a ManageDeclarationPartitionRequest funkciónál. A leírás alapján képezzük a requestSignature értékét, vagyis az interfész leírás 2.4.1 pontja alapján. A feltöltése a fájlnak szintén a leírás alapján bytestreamként történik. Mit nem vehettünk figyelembe? 
Adatok:
requestID: E28_25IDSr5Zt3Bc2Y_S_
timestamp: 2024-02-19T07:24:00.000Z
A fájl SHA3-512 lenyomata, ami feltöltésre kerül: 5D9706035BA2C4B6A4E3DC898F1C5F405ECE049FBAAE04B0DF05999BF7D5FD3433188B1D011B3C67251B0796E5ABFDD1180F1FF2E0E43F55409B3B4696E4F308

Az adatok a teszt rendszerbe való küldéste vonatkoznak.

**Comment by jsz66** [comment]
Megoldódott!

**Comment by fabibandi** [comment]
Kedves [jsz66](https://github.com/jsz66), megvan még hogyan oldódott meg? Én ugyanezt a hibát tapasztalom, és többször ellenőriztem mindent, több xml-lel próbálkoztam, de nem oldódott meg.

**Comment by jsz66** [comment]
A problémát az okozta, hogy a felérkezett stream más volt, amiből a HASH számolva lett. A fájl feltöltés lett elrontva, így a NAV szerver által számolt HASH jogosan nem egyezett meg a kérésben szereplő HASH értékével.

**Comment by fabibandi** [comment]
Továbbra sem találok problémát a mi oldalunkon. Én úgy értelmeztem a doksit, hogy az xml-ből kell számolni a hash-t,. Te is abból számoltad, vagy a zippelt fájlból?  Az egész kérést lementettem, és benne van az octet-stream része adattal együtt. Nem emlékszel nálatok mi volt pontosabban a probléma? Valami karakter kódolás esetleg? Köszi a segítséget előre is!  Ha nem boldogulok adok fel én is egy jegyet.

**Comment by jsz66** [comment]
A gz fájból kell számolni. Mutatok egy példát:

requestSignature:
SHA3-512([requestId][maszkolt timestamp][technikai felhasználó aláírókulcsa][SHA3-512(evat202403.xml.gz)])

requestId: VSKERES_007_
maszkolt timestamp: 20240424190000
technikai felhasználó aláírókulcsa: 3y-b914-0267a28b3b6c4GZ3XOMX4CC9
SHA3-512(evat202403.xml.gz): B2F4564468F88B027ED79F5878C401E1C2EEA87B5266156A760C04331BB858FD82A9DD7BE0703729633D3132DF81268A89D4915DB2E3C30820EEB918E84E70FB

SHA3-512(VSKERES_007_202404241900003y-b914-0267a28b3b6c4GZ3XOMX4CC9B2F4564468F88B027ED79F5878C401E1C2EEA87B5266156A760C04331BB858FD82A9DD7BE0703729633D3132DF81268A89D4915DB2E3C30820EEB918E84E70FB)

requestSignature ezek alapján: C3DBD17D9495B221DB07AC70E5C9D0FF7AB31D9DB418F855F597807C515A617003A8D92D788F5CA729114915327A2057D210C299A27D011F658B8DE43DF71194

Ellenőrzéshez javaslom a következő online SHA kalkulátort: https://www.strerr.com/en/sha3_512.html

**Comment by fabibandi** [comment]
Nagyon köszönöm, kipróbáltam, működik. Üdv, és szép hétvégét!
