### ISSUE TITLE
Jogosultság szükséges

### ISSUE THREAD

**Issue by davidotvos** [nav-gov-hu/eVAT#115]
Sziasztok!
Olvastam itt már több embernél hogy a /queryTaxCodeCatalog hibára fut. Nekem is ez lenne a gondom, akármit próbálok mindig jogosultság szükséges a válasz. Online számlában van megadva jogosultság, viszont az eáfa teszt oldalán a bejelentkezés is az online számla oldalára irányít át.

RequestID: ODOObb62f7344556454886185ebcd9
Timestamp: 2024-02-26 08:02:21.616122

**Comment by NTCA-KZJ** [comment]
elméletileg ez már nem lehet hiba

**Comment by davidotvos** [comment]
Igen, már megoldódott!
