### ISSUE TITLE
queryDeclarationList végpont üres válasz, miközben a webfelületen van tartalom

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/eVAT#120]
Sziasztok,

A teszt rendeszer webes felületén látszanak különféle állapotú bevallások, viszont a queryDeclarationListResponse -ban viszont üres listát kapok.

A webes állapot:
![image](https://github.com/nav-gov-hu/eVAT/assets/33445911/d3eb5cf8-4a29-4f3d-b813-c601058c5036)

A válasz XML:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryDeclarationListResponse xmlns="http://schemas.nav.gov.hu/EAR/1.0/api" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/EAR/1.0/data" xmlns:ns4="http://schemas.nav.gov.hu/EAR/1.0/base">
	<ns2:header>
		<ns2:requestId>986318189e5048fc8e8f386c680a04</ns2:requestId>
		<ns2:timestamp>2024-04-10T09:50:52.714Z</ns2:timestamp>
		<ns2:requestVersion>1.0</ns2:requestVersion>
		<ns2:headerVersion>1.0</ns2:headerVersion>
	</ns2:header>
	<ns2:result>
		<ns2:funcCode>OK</ns2:funcCode>
	</ns2:result>
	<declarationList/>
</QueryDeclarationListResponse>`

**Comment by zbenko** [comment]
Kedves @vectorkovacspeter 

én korábban úgy olvastam (https://adozona.hu/afa/eAfa_bevallas_M2M_2_resz_TI4FER) , hogy webes és gép-gép felület nem átjárható, az egyikben létrehozott adat a másikban nem látható, és fordítva, mivel a két rendszer logikája teljesen eltér egymástól. Azóta nem olvastam róla, hogy ez megváltozott volna.

**Comment by NTCA-KZJ** [comment]
Kedves @vectorkovacspeter
A gépi interfészen a lekérdező szolgáltatás csak a gépi interfészen feltöltött analitikákat adja vissza.

**Comment by vectorkovacspeter** [comment]
> Kedves @vectorkovacspeter A gépi interfészen a lekérdező szolgáltatás csak a gépi interfészen feltöltött analitikákat adja vissza.

Értem, ez elkerülte a figyelmemet, köszönöm a választ.
