### ISSUE TITLE
Beküldött ÁFA analitika PROCESSING státuszban áll

### ISSUE THREAD

**Issue by tmorucz-mazars** [nav-gov-hu/eVAT#123]
Üdv,
Volt már egy lezárt issue a témában, melyben jelezték, hogy a hiba javítva lett, de én jelenleg is ezt tapasztalom.
Teszt rendszeren küldtem be három ÁFA analitikát különböző hónapokra:
Január: 4KV3ZMA0E4OFB5DF
Február: 4KV3ZXWOPZGAPRDV
Március: 4KV40BUWZ73R4IDZ

Mindhárom PROCESSING státuszban áll 6 napja (május 15 óta).

Lehet tudni mi okozza ezt? Hiba lehet a bevallásban, vagy szerver oldali probléma?

Köszönöm a segítséget!

**Comment by NTCA-KZJ** [comment]
Tisztelt Bejelentő!
A hiba kivizsgálása folyamatban van.
Annak eredményéről tájékoztatom.

**Comment by NTCA-KM** [comment]
Tisztelt Bejelentő!

A hiba javítása a tegnapi napon az EDU síkra történt új szervíz telepítésével megtörtént. Kérjük, ellenőrizze a korábbi beküldés rekordjait, vagy tesztelje újra a folyamatot. 

Üdvözlettel:
Informatikai HelpDesk
Nemzeti Adó- és Vámhivatal Informatikai Intézete
E-mail (eÁFA M2M): eafa_m2m@nav.gov.hu
