### ISSUE TITLE
manageDeclarationUpload vs. manageDeclarationPartition

### ISSUE THREAD

**Issue by uicodework** [nav-gov-hu/eVAT#125]
Üdv!

A leírás alapján nem világos hogyan és hova kell beküldeni a bevallas xml-t.
A felöltés azonosítót megkapom manageDeclarationUpload-al. Ez eddig OK.
A bevallás beküldésénél viszont elakadtam.
A leírásban ez szerepel:
3.3.3 pontban:
"A /manageDeclarationPartition az áfabevallás analitika beküldésére szolgáló operáció. Ezen keresztül van lehetőség a bevallás analitika partíciót a NAV számára beküldeni."
Viszont a következő oldalon a Leírás és kapcsolódó követelmények részben ez szerepel:
"A POST /manageDeclarationUpload végpont számára 'multipart/form-data' (RFC 2388) formátumú kérést kell küldeni, mely két üzenetből áll. ..."
Most akkor melyik végpontra kell beküldeni?
köszönöm

**Comment by NTCA-KM** [comment]
Tisztelt Bejelentő!

Legyen kedves az eafa_m2m@nav.gov.hu címre elküldeni azt a telefonos elérhetőségét, amelyen kollégánk felveheti Önnel a kapcsolatot.

Köszönettel,
Informatikai HelpDesk
Nemzeti Adó- és Vámhivatal Informatikai Intézet

**Comment by NTCA-KZJ** [comment]
A bevallás feltöltésének kezdeményezése a POST /manageDeclarationUpload végponttal történik, amely az analitikát hash-elt formátumban kell tartalmazza.
A bevallás partícióinak feltöltése a POST /manageDeclarationPartition végpontokon történik.
Az [eÁFA M2M rendszer interfész specifikáció v0.7](https://github.com/nav-gov-hu/eVAT/blob/master/docs/spec/eA%CC%81FA_M2M_rendszer_interfesz_specifikacio_v0.7.pdf)-ben, a 3.3.3 /manageDeclarationPartition operáció fejezetben, a “Leírás és kapcsolódó követelmények” résznél a leírtak alapján a partíciók leképzése szükséges.
A folyamat leírása: "A partíciók képzése a következő módon történik. A kliens a véglegesített earData.xsd alapján képzett bevallási XML-nek kiszámítja az SHA3-512 hash értékét, majd az objektumot gzip formátumba tömöríti. A kliens ezt követően - attól függően, hogy a tömörített objektum mérete átlépi-e a maximális partíció méretet - meghatározza, hogy a feltöltendő bevallás hány partícióból fog állni. A kliens a maximális partíció méret betartásával byte tömbökre feldarabolja a tömörített állományt és bytestreamként a multipart REST request 'application/octet-stream' üzenetében feltölti".
