### ISSUE TITLE
eÁFA Standard adókód kérdések

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#19]
Megnézve a Standard adókódokat, és annak a képzését, az látszik, hogy a mostani ÁNYK 2265 bevallás van benne leképezve, és a kódképzési módszer elvileg tényleg alkalmas a kódok bővítésére is. Azonban több kérdést fogalmaznék meg:
1.	Ha egy szoftver mondjuk képes lenne a bizonylat kiállításakor (számlakibocsátó esetén) azonnal ellátni a számla tételsorait Standard adókódokkal, akkor ismerni kellene az akkor alkalmazandó adókódokat, ami a valóságban nem biztos, hogy ismert.  Pl. 2023.01.02-án kiállítok 2023-ban teljesített 27%-os belföldi termékértékesítésről egy számlát, a szoftverem ellátná adókódokkal, azonban ekkor még nem jelent meg a 2365 ÁFA bevallási nyomtatvány, tehát nem tudható teljes bizonyossággal az, hogy ezt milyen kóddal kell ellátni, mert lehet, hogy az ÁNYK 2365-ben ez már a 08. sor lesz majd, ezért nem a 2022-ben használatos „MP07 KVR V27” kell majd, hanem a ÁNYK 2023-beli „MP08 KVR V27”.
2.	A fenti példa tovább sarkítható, ha 2022.01.02-án kiállított számláról éves áfa bevallás készül majd 2024.01.20-ig. Addig nagyon sok minden megváltozhat akár a jogszabályi környezetben, akár a NAV elvárásában, ami a standard adókódokat is érintheti.  Ezt hogyan lehetne kezelni?
3.	A standard adókódok nem tükrözik a Nyomtatvány évszámát sem. Adóalanyként ismeretlen a nyomtatvány változásának módszere. Pl. ha a 2265-ben a 07. sor a 27%-os áfa kerül, akkor „MP07 KVR V27” kódolás kell, azonban lehet, hogy a 2365 nyomtatványban a 07. sorban a 26%-os áfa lesz. Akkor úgy nézne ki a kód, hogy „MP07 KVR V26”?
4.	Számla tételsor utólagos módosítása (régiesen: helyesbítése) számlával egy tekintet alá eső okirattal esetén az eredeti standard adókóddal kell ellátni, vagy a módosítás pillanatában aktuális standard adókóddal?  Példa: A lánckezdő eredeti számla „MP07 KVR V27”-el lett ellátva, mert 27-%-os áfa kulcsú volt 2022-ben, de 2023-ban módosító okirat lett kiállítva szintén 27%-os áfával, de akkor már nincs mondjuk 27%-os áfa kulcs, és az ilyen számlának a 2265-beli 35. sorba kell kerülnie és így MP35 adókóddal kellene bevallani, vagy az eredti „MP07 KVR V27” kóddal?  
5.	Az ÁFA törvényből nem következik ennyi, 236 db adókód (és igazából még az 2265 bevallás 1-101. sora sem), ezek egy része csupán a NAV saját készletezésre való adatgyűjtése. A kérdés az, ha valakinek a bevallása megfelel a törvényeknek, de nem követi le a Standard adókód mélységét, azaz mind a 236 db kódot azt elfogadhatóan jár-e el? Pl. a „MP07 KVR V27” -ot használja a tárgyi eszköz értékesítésre is, és nem a „MP07 DP43 KVR V27”-et?
6.	Mit jelent a két utolsó Standard adókód?  „KTEV VVKSZ” és a „KTEV VVKFSZ” ? Ezeket mire lehet használni, mert nincs ÁNYK 2265 nyomtatványbeli megfelelője.

**Comment by NTCA-HM** [comment]
Kedves @Macskafarka !

A standard adókód lista az Áfa tv.-ből levezethető összes bevallás releváns ügyleteket tartalmazza. Jellemzően egy-egy ügyfélnek ennél lényegesen rövidebb a saját maga által használt adókód listája. Éppen ezért érdemes a könyvelő program ügyféli testreszabásánál a vállalkozás által használt adókódokat összerendelni a standard adókód párjával és nem feltétlenül hasznos a teljes standard adókódlistát implementálni az ügyféli rendszerbe. Az adókódok megfeleltetésénél érdemes gondolni arra, hogy a NAV oldaláról a standard adókódok időben változhatnak. A standard adókódok változása, ha érint ügyféli vállalati adókódot, akkor annak kezelése mindenképpen kliens oldali kötelezettséget jelent. Érvényét vesztett standard adókód használata esetén a data XML-ből nem képezhető áfabevallás.
