### ISSUE TITLE
Sémák validálása

### ISSUE THREAD

**Issue by szepeviktor** [nav-gov-hu/eVAT#22]
Biztos vagyok benne, hogy nem beszélek XML nyelven.

```
$ xmllint --noout --schema XMLSchema.xsd common.xsd
common.xsd validates

$ xmllint --noout --schema common.xsd earBase.xsd
earBase.xsd:8: element schema: Schemas validity error : Element '{http://www.w3.org/2001/XMLSchema}schema': No matching global declaration available for the validation root.
earBase.xsd fails to validate
```

A common sémát lehetett validálni ezzel: https://www.w3.org/2012/04/XMLSchema.xsd
Ám az earBase-t nem. Lehet nem is a common-ból származik??
Sajnos nem értek hozzá, de lehet van valami javítani való.

**Comment by renced42** [comment]
Kedves @szepeviktor 

Ha megnézed az importot az earBase common névtere a http://schemas.nav.gov.hu/NTCA/1.0/common -ból jön.
Nem ismerem az xmllint-et, de, próbáld meg azt, hogy a earBase.xsd-ben az xs:import-ot kiegészíted így:
`<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation="common.xsd"/>`
Általában a namespace eléréseket az xsd, xml szerkesztő programokban be lehet állítani, így azokat automatikusan megtalálja.

Annyi bibi van, hogy a common.xsd-t a https://github.com/nav-gov-hu/Common repoba fogjuk véglegesen feltenni, ma vagy holnap új RC tag-en. Addig marad itt.

**Comment by szepeviktor** [comment]
> az xsd, xml szerkesztő programokban

Értem.
A bitek szintjén dolgozok, a "jéghegy" víz alatti részén.
Az xmllint a minden xml anyukája `libxml2` parancssoros eszköze.
