### ISSUE TITLE
MOL Group - Kérdések az e-VAT tervezéssel kapcsolatosan - 2023. március 07.

### ISSUE THREAD

**Issue by inyiri** [nav-gov-hu/eVAT#26]
Tisztelt Kollégák!

A mellékelt excel file tartalmazza a kérdéseinket a március 7-i konzultációhoz.

Köszönettel,
Nyiri Imre
MOL
inyiri@molitdgbs.com
[MOL kommentek összefoglaló.xlsx](https://github.com/nav-gov-hu/eVAT/files/10860523/MOL.kommentek.osszefoglalo.xlsx)

**Comment by renced42** [comment]
Köszönjük.
