### ISSUE TITLE
MOL Kérdés - 2023.03.21

### ISSUE THREAD

**Issue by inyiri** [nav-gov-hu/eVAT#32]
Kérjük szíves tájékoztatásukat, hogy amennyiben az adózó a NAV által kiajánlott áfa analitikát bevallásként elfogadja és a külön applikáción jóváhagyja, milyen módon fog visszajelzést kapni a beküldés megtörténtéről és az adóhatóság általi fogadásról (jelenleg feladási igazolást és letöltési igazolást kapunk a cégkapun keresztül).

Köszönettel,
MOL Group

**Comment by NTCA-tax** [comment]
Az applikáción keresztüli külön jóváhagyás szükségességét a visszajelzések alapján még átgondoljuk. Jelenleg nagyon afelé hajlunk, hogy erre ne legyen a folyamatban szükség.

A bevallás beküldéséről továbbra is a jelenlegi szokásos nyugták visszaküldésre kerülnek a cégkapun keresztül. Ugyanakkor a beadott és feldolgozott bevallás M2M-ben is lekérdezhető.

**Comment by renced42** [comment]
Kedves @inyiri 
Mivel nem lesz külön app jóváhagyás ezt a kérdést zárom. Kérem, hogy a szakmai kérdéseket a Discussionban tegyétek fel.

Köszönöm szépen!
