### ISSUE TITLE
application.wadl nem lett publikálva

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/eVAT#53]
NAV-OSZ esetén publikálva lett : https://github.com/nav-gov-hu/Online-Invoice/blob/master/sample/WADL/application.wadl

Jó lenne, ha itt is elérhető lenne.

Köszönöm.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
Bocs a késői válaszért megnézem mit tehetek.

**Comment by EPluribusUnum** [comment]
@renced42 , várható ezügyben valami?

Köszönöm.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 

Igen, köszi a türelmet. Nem készült WADL, de felvették a fejlesztő kollégák taskra. Ha készen van jelezni fogom.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 

A WADL itt megtalálható:
https://github.com/nav-gov-hu/eVAT/tree/master/src/wadl
