### ISSUE TITLE
Le nem vonható sorok kódolása

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#54]
Hogyan kell eljárni akkor, amikor a befogadott számlán lévő tételsorok között van olyan, amit a számlabefogadó nem kíván levonásba helyezni, pl. mert a számla kiállítás után derül ki, hogy az nem a vállalkozás érdekében került megvásárlásra? Az xx65 ÁNYK bevallás esetén egyszerűen kihagytuk a 64-65-66 sorokból a számlának ezt a sorát, azonban a számla teljes összegét szerepeltettük a xx65M-02 lapon. Az eÁFA-ról az a mondás, hogy kiváltja az M lapokat (amelyen szerepelne a levonásba nem helyezett tételsor összege is).
Ugyanakkor a Standard adókódokat csak azokhoz a számla tételsorokhoz lehet képezni, amelyek bekerülnek az xx65A 1-101 sorokba is. Konkrétan mi a teendő a levonásba helyezni nem kívánt sorral:  egyszerűen ki kell hagyni az eÁFA-ból, vagy lesz rá egy külön kód, amivel meg lehet különböztetni a szándékosan  levonásba nem helyezett sort a véletlenül kihagyott sortól?  Ellenőrzi-e a NAV azt, hogy gép-gép kapcsolattal beküldött eÁFA bevallásban a standard adókóddal ellátott sorok összege nem adja ki számlakiállító általi adatszolgáltatásban szereplő bizonylat bruttó összegét? És ha igen, akkor vajon WARN, vagy ERROR jön majd erre?

**Comment by renced42** [comment]
Kedves @Macskafarka 

Szerintem a keresett standard adókód:
KL V00	L00	véglegesen kivett számlatétel  (210. sor a publikált utolsó excel táblázatban)

**Comment by Macskafarka** [comment]
Igen, Köszönöm a választ! Még a 2022--ben kiadott kódokat néztem.

**Comment by Macskafarka** [comment]
Ha a befogadott számlán egyetlen sor szerepel, amelynek az áthárított egyenes áfájának csak egy részét szeretném levonásba helyezni, azt hogyan kell  adókóddal ellátni? Most nem a telefon áfára gondolok, hanem arra, amikor a felhasználás körülményeiből következően nyílik meg a levonásba helyezési jog. Ilyen pl. gázolaj beszerzésnél annak egy részét munkagépbe felhasználva levonható, más része viszont nem vonható le, mert  személygépkocsiba lett felhasználva. A kérdés lényege az, hogy egyetlen számlatételsort kellene két különböző adókóddal ellátni.

**Comment by renced42** [comment]
Ezt még itt megválaszolom:

Ha arról van szó, hogy az Áfa tv. 124. §-a vagy 120. §-a alapján (ide nem értve az arányosítással érintett eseteket) az adóalany az áfának csak egy részét vonhatja le, akkor ebben az esetben is egy adókódot kell a tételre tenni ami megmondja, hogy az adott tételből mennyi kerül levonásba. A másik nem levonásba helyezett részt, nem kell adókódolni.

Kérlek, hogy a szakmai kérdéseket a discussionba tedd fel.

Köszönöm szépen!
