### ISSUE TITLE
ATK kód használatának indoka

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#55]
A közzétett standard adókódok között szerepel az ATK,  "áfa tárgyi hatályán kívüli" ügylet leírással. Kérdésem: van-e annak jogszabályi alapja, hogy az ÁFA tv. hatályán kívüli ügyletről az ÁFA tv. alapján bevallást kellene benyújtani?

**Comment by Macskafarka** [comment]
Arra tudok gondolni, hogyha elindul az italok csomagolására az 50 Ft-os visszaváltási díj, akkor azt külön tételsoron kell szerepeltetni a számlán. Ez a sor nem tartalmaz felszámított áfát, és így levonásba sem helyezhető. Kell-e egyáltalán szerepeltetni az eÁFA bevallásban pl. ATK kóddal, vagy sem.  Ha akár számla kiállítóként, akár számla befogadóként nem szerepeltetik, akkor ERROR jön rá, vagy WARNING? Ugyanis meglátásom szerint az Áfa tv. -ből nem lehet levezetni azt, hogy be kellene vallani azt, amire az áfa tv. NEM vonatkozik. Tudom, hogy lesznek, akik beküldik ezeket a sorokat a bevallásba, de vajon muszáj-e?

**Comment by renced42** [comment]
Kedves @Macskafarka 

Kérlek, hogy ezt a kérdést a discussionba tedd fel.

Köszönöm szépen.
