### ISSUE TITLE
TaxCodeCatalog táblázat

### ISSUE THREAD

**Issue by tothj74** [nav-gov-hu/eVAT#62]
Az eddig publikált két adókód táblázat szerkezete jelentősen eltér. 
A feldolgozó modulunk az elsőként publikált táblázatra épül.  Van arra lehetőség, hogy elérhető legyen a teljes továbbra is?

**Comment by Szildiko** [comment]
Felkerült a NAV honlapjára a 2465 tervezet. Meglepő módon a 0%-os áfa sorokat beszúrták új sorszámmal, ahelyett, hogy a sorok csúsztak volna. Ez kicsit azért fura, mert évközben szoktak ilyen módszert használni, év elején azért sorokat tolnak. Érdeklődnék, hogy esetleg az eÁfa miatt csinálták így, hogy saját rendszerben már ne kelljen sorokat tologatni? Persze a tervezet még módosulhat, de mivel azért az eÁfánál is munkával járhat a standard adókód változtatása, így gondolom azért alaposan megfontolják mit csináljanak. Ha nem ehhez a topichoz tartozik kérdésem, akkor bocsánat.

**Comment by PeterAdam** [comment]
Saját tapasztalat szerint a változás évében beszúrás, az első "nyugodt" évben átsorszámozzák. Minden évben van miről beszélni a teljesítményértékelésen.

**Comment by renced42** [comment]
Kedves @tothj74 nem teljesen értem a kérdést!

"Van arra lehetőség, hogy elérhető legyen a teljes továbbra is?"
Teljes mi?

Köszi!

**Comment by tothj74** [comment]
Kedves @renced42 
Köszönöm a választ.
Teljes táblázat alatt az eredetileg publikált NAV_STANDARD_ADOKOD_20221024.xlsx-ben látható formátumot értettem, melyhez képest a TAX_CODE_CATALOG_20231026.xlsx formátuma jelentősen csökkentett adattartalommal bír.
A központi e-mail címről időközben azt a választ kaptam, hogy az utolsó verzió (TAX_CODE_CATALOG_20231026.xlsx) a mérvadó és a 2024-es táblázatot is így kapjuk. 
A választ elfogadtam, megtörtént a feldolgozó rutinunk átírása erre az új formátumra, így az eredeti kérésem tárgytalan. Igazából csak meg akartam úszni az átírással járó pluszmunkát.😊
