### ISSUE TITLE
ManageDeclarationPartition válasz

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/eVAT#63]
### Discussed in https://github.com/nav-gov-hu/eVAT/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **bmatyi94** December 19, 2023</sup>
Van aki sikeresen kap választ a ManageDeclarationPartition request-re? Nálam nem jön vissza response, timeout, pedig nem nagy a gzip analitika mérete, a teszt analitika ami feltöltésre került ide a github-ra azzal teszteltem.</div>

RequestID: c1d4bd7760a947f6a638f205e732ff

**Comment by renced42** [comment]
Kedves @bmatyi94 
Kérlek ellenőrizd.

**Comment by bmatyi94** [comment]
> Kedves @bmatyi94 Kérlek ellenőrizd.

@renced42 Köszönöm, végre működik.
