### ISSUE TITLE
Teszt rendszer hiányzó jogosultság

### ISSUE THREAD

**Issue by adamat74** [nav-gov-hu/eVAT#66]
A NAV Online Számla teszt rendszerben nem elérhető a "Hozzáférés e-Áfa rendszer interfészhez" jogosultság.
Hogyan lehet ezt a jogosultságot beállítani a teszt rendszerben? Köszönöm

**Comment by renced42** [comment]
Kedves @adamat74 

Az Online számla rendszerbe ha belépsz elsődleges userrel a Felhasználók menüpontot kell választani.
Ott egy technikai user sor végén a részletek oszlopba kell kattintani, majd a Zöld módosítás/Jogosultságok módosítása menüre.

**Comment by adamat74** [comment]
Köszönöm. Most be tudtam állítani. Ki is próbáltam. Működik.
