### ISSUE TITLE
/manageAttachmentUpload FILE_TYPE_MISMATCH png és jpeg kiterjesztésnél

### ISSUE THREAD

**Issue by Reterics** [nav-gov-hu/eVAT#67]
A **/manageAttachmentUpload** végpontja megpróbáltam teszt fájlokat feltölteni. **png** illetve **jpeg** formátumban, de mindkét esetben **FILE_TYPE_MISMATCH** hibát kaptam vissza.

A képeket ugyanolyan módon töltöttem fel mint a ManageDeclarationPartitionRequest esetén, (octet-stream) majd megpróbáltam gzip tömörítés nélkül is.

Request IDk: 
- Tömörítés nélküli PNG feltöltés: RID073958300170462940858477
- GZIP PNG feltöltés: RID037398200170462943382568

A fájl beolvasását egyszerűen file_get_contents()-el végzem, esetleg itt hibázhatok valahol?

![NAV_eVAT_attachment](https://github.com/nav-gov-hu/eVAT/assets/13684826/edabd56f-cffc-4b0b-8489-46a03b310a37)

**Comment by renced42** [comment]
Kedves  @Reterics 
A filename mezőbe írd bele a rendes file nevet kiterjesztéssel, ne kiterjesztés nélkül.

**Comment by Reterics** [comment]
> Kedves @Reterics A filename mezőbe írd bele a rendes file nevet kiterjesztéssel, ne kiterjesztés nélkül.

Működik, köszönöm!

**Comment by csillagd** [comment]
Nekem ugyanez a problémám, hogy állandóan FILE_TYPE_MISMATCH-ot kapok, pedig a fájlnév mezőben benne hagyom a kiterjesztést. Ennél a requestnél szükséges a fájlt tömöríteni? Ha tömörítem, ha nem, ugyanezt a hibát kapom.
Van esetleg egyéb vizsgálati szempont, ami alapján elhasal a requestem?

Alább a Fiddler által logolt nyers requestem (az octet-stream rész elejéből látszik, hogy még a Fiddler is PNG-nek nézi):
***********************************************
POST https://api-test.eafa.nav.gov.hu/analyticsService/v1/manageAttachmentUpload HTTP/1.1
Host: api-test.eafa.nav.gov.hu
traceparent: 00-09b8f5a615c14b0766668cdb2e7402e7-1171f3a15b8b61cf-00
Content-Type: multipart/form-data; boundary=03f4a88b-95cb-4ce5-a097-6874f30d473e
Content-Length: 16308

--03f4a88b-95cb-4ce5-a097-6874f30d473e
Content-Type: application/xml; charset=utf-8
Content-Length: 1799
Content-Disposition: form-data; name=body

<?xml version="1.0" encoding="utf-8"?>
<ManageAttachmentUploadRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.nav.gov.hu/EAR/1.0/api">
  <header xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
    <requestId>TRS202411070716493240</requestId>
    <timestamp>2024-11-07T07:16:49.001Z</timestamp>
    <requestVersion>1.0</requestVersion>
    <headerVersion>1.0</headerVersion>
  </header>
  <user xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
    <login>gufc4g2hkrcwy9l</login>
    <passwordHash cryptoType="SHA-512">794788485599F39E7F1886F72370827612B8BF7F1043597A659DA3D2525AA34D60D1F954BE2A6A91E9449CF933246600A75A6396EE43382A7B89F469CEB5964B</passwordHash>
    <taxNumber>12558775</taxNumber>
    <requestSignature cryptoType="SHA3-512">022CF3DDA278C5C9A1D30883F49803E82E40EEAE82BBF4A249DC6D9D89C1C6558175E433C6ECBA6F947E915AA655FBF2F7BDC703B2178FB6F59C7CBE22652213</requestSignature>
  </user>
  <software>
    <softwareId>TREND0000061805281</softwareId>
    <softwareName>TREND vállalat-irányítási rendszer</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>6.18.0717.1</softwareMainVersion>
    <softwareDevName>TR-Soft 2000 Kft.</softwareDevName>
    <softwareDevContact>+36 1 358-11-20</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>12558775-2-43</softwareDevTaxNumber>
  </software>
  <fileName>Névtelen.png</fileName>
  <fileExtension>PNG</fileExtension>
  <contentHash cryptoType="SHA3-512">CAFE0E92FAC1A6ACB8BD8D3346133312CA58FEF5505147ADC3DDB51D658F032BC67F739CB4A9729520C41740189BB46C0B311CA4F73F7F61D737A21B2E322113</contentHash>
</ManageAttachmentUploadRequest>
--03f4a88b-95cb-4ce5-a097-6874f30d473e
Content-Disposition: form-data; name=file
Content-Type: application/octet-stream

 PNG

   
IHDR        Ρ   sRGB       gAMA    
 a   	pHYs       o d  6 IDATx^  [  F $    {  f   x   zD ? @    $I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K҅      $I  +I?@? wM  9   t   j %Iz̯ $  ~ ڹI   Q   v $i7~ $) D H      -  g $IM  I   3 $i* ` jя iMF{ %IS ŒT ~ ]5    I U   4  B :߫$IW I (    w >~ $  _!I G?  Ns    $  /  K Jg >t g%Ig k# 2    i_ < $ /    >G& B ˑI 7 U t:  sTһ y:*I  _I  2G$   #  w   t  rD   9<"Iz _I_G?N  t% ~3Iz /    " L    o&Iį   Џ o%MG      WA [ G 7 Z    $ /   я o$ ރo$i_~$=D?>Mҟ   4I  ͗t X $I  { I   / _   'Iz
 G $  o     $ s n}  N      'I: o $  o  1 G n  A  'I   ,m      ߢ   $  [,m      k    $   +m  q   k    $  +   $iz  I   R!   j :   j   7U*B  _MR'z _M u  J  I    & z|3    +I }^Iҵ VJC ? W  ?   $] o 4 S}%틞 + ߠ x%I  [(
A D_M   `R:  +I 
 >i    J =
   ^I  | 
    }  09   +I: o tQ   $z.  ߡ x6I  m .  )>   z6  ѽ<  c  IB  M =M   ^^I 1|  
 | &%zF  u  <    ͒~   = D Yɮ   5]
 ѳI  ( G ܳI       yM C  l  ÷I    L =  dS ߞ 辞I  |   ? g   &    5] ׳Iz o t   L 3  Y    L G  L    #  i=  
z  ihC 9   I k|k  ? g ^E Q6
m 4
  3Iz o t   L ; Yʦ 
k    Q    "} Sz& ] < MD;2 Dw L   -    =  	z   hK   > I m !җ ? GI @ V6m 4  $1  
 ϣ o  +    i>  g  O    ͣ o  ,   d A  (I  D `%}=gk ўL] % O 
  ˣ #г MG 2  {~ $ K/ (   D \6m ԋ  ^  |
 ' ? GIG  .  6e Fw (iW>   ǣ 3г MG  ԍ  QҎ|   ƣ    5 ]  ѽ?JڍO t     t6z  + >   %  '^   A K z  + ^    
 v	 ? {I @ bւ e =      K  <J z  -Ӟ Yx   '\ ?  ^ү s   m  F Ľ V>   G {IW@ fւ e=   dk{    t |f-h[&    {Im|  5   K zF & /  @ ƽ &>  }  %]
= YڗI   ^R
 fm >      լ	 ˤD Ƚ >  }  %]= YڗI+zN %M S  Ї ^ҕ 3 5 } t
=/  & 	 6 ~+       L    [IS  j
 ᾕ4= YژI  ss+i" \գ   )      Lz=;    U5 P J    
m̤g  s+i Xբ  i 9    Lz=C    iU% 0 J    
m̤W st+i Tա򭤩 y    Lz =K   ΧTU C|+i2z  6 1  E ӭ + 	U
   J     ̤w  t+ |:U >   г 5    	z n%] O * G  Z  5    )z n%] O ƣ -%5 g<kD;3  ٢    h   6 g hg&}
=_ t%>  >     s 5    M Q U 4j$   JjD zֈvf 7 3v+ 
|5}Po%   =kD;3   9   k>  >     3 5   tz n%  O Ơ譤v  g hg&   [I  ӧ1  II; g?kD;3 H  Qү  i pR .     L:=w  
>y < `R N    L:={ t6 :]}()i'  5   tz ( L>q , @ J 	 k hg&    [Ig i e Ǒ vC  Z#ڙIg g    ӦK #   y^1   Z#ڙIg 琒   ˡ"   9NJ   Z  L z) h>e  Rz  Ĵ [ښ   
 vSґ| t)   :    $kE[  9\ V  V Q| t   :ÆvF瑵   n &Ԋ R Q| t	   :ævEg     Nh  Z VJ: O ~ >x ^G  Ԯ , V 5 m X+ JI  S       6 #:  m vAۧ֊  I  S      9 ]  k; s Z  l  {r h+%} O ~ >p  Cg MA  n  V 5  \3 KI  Ӥ   ۚ Cg 6  k  3 Z  l  ;  ך ^J  $ } (   2  6d  3 Z ֬m^ " ; f     'I     yf І     m      o]kF{) S>E:}   >:ϵ hG ڟ   Y;ڜ]  k h3%} 'H      yfSіl' ?kE[ f w     v@ פO  4   : l*ڲ 
ڞ   Y3ڛ]   h7% ˧G   ך>G MF{ ]   m͚     o^  ^   ӣSЇkM  s]   d   Y+ښ5    wg   k ;|rt8 `Q  k6m vA۳V 5kE[ &  ; m  W   p Z w  f Ѧl =kE[ V 5    l' Mz O E*J Ag MG  v@  V 5kE[ ) o_ 	 _ ^          f
hW ڝ   Y+ښMB  OI  i a 㴦  ]k@    m Z  l      I  i !  D { |  -   Z ֬ \    l7t    >Jk .: m v@  V 5kD; ihC #: 5 >) :     蜳 -   Z ֬ ̦ 
ٮ ,֤G|J u 1Z   9gMh_֎6g hkֈvfюlGt t O   >Bk: uք e hs֊ f hg6  vEg &      c YgMh_֎6g hkֈvfюlWt t O   >>k: wք e hs֊ f hg6  vF &  ӡ  Ϛ C睵  Y;ڜ   Y#ڙMD;  љ I 'C_A 5  ;kC v 9kE[ 6 1   d  3Y  O >F 5  <kC v 9kE[ 6 1   dz|F$ |* 1 ج Xt Yژ   Y+ښ    T %  3 #i S  ЇfMǣs   Ƭm Z ֬
m̦ -  Dg &% } >2k: {ֆ6f hs֊ fmhc6m  ': 5) D m Y 9  F 3kF{ V 5kC  hK     I i   㲦s  g hg֌ f hkֆ6f ўL  Y   Ӡ ЇeM    ά  Z ֬
m & =  F &  'Ao  ʚ C 5  Y3ڛ   YژMF{2   gM  O ^F 5    kD; f 7kE[ 6 1   d ': 5ɧ@/  ɚ Ew 5  Y3ڛ   YژMF{2      % Y    F 3kF{ V 5kC  hO  sZ  |     |tY#ڙ5  Y+ښ    d 'ӿ 9 io>z}@  tY#ڙ5  Y+ښ    d '  ZӾ }= >k 
    ̚ ެm    l2ړ  Y i_޾ B 5   Z#ڙ5  Y+ښ    d ' mt^kړ7   GcM Aw ֈvf ho֊ fmhc6  t ך    ! `  w >  ά  Z ֬	 [   d   lM    },  ;tY+ښ5  Y+ښ5 }k ўL љ i?޺  E ߢ; Z ֬  Z ֬	 [   dz  - ~ u E 5  I֊ f ho֊ fMh_6m   ۚ   . Hd =   m͚ ެm͚оl:ڔ 9tv    & @    ^ V 5kF{ V 5kB   hS   ٭i޶n  Ú~  %kE[ f 7kE[ & /  6ez _ }xۺ >    &kE[ f 7kE[ & /  6ez _ }x B aX 5  d hk֌ f hkք e ѦLϣ [  i! (d    m͚ ެm͚оl:ڔ 5t    M _胰    Z ֬  Z ֬	 ˦ M ^Cg  ~޲  >k    m͚ ެm͚оl:ڔ 5t k  - _ c  Z莲V 5kF{ V 5kB   hS   9f  -  C  k ; Z ֬  Z ֬	 ˦ M ^G縦nް  >    )kE[ f 7kE[ & /  6ez e nް  >    )kE[ f 7kE[ & /  6ez e nް  > k    m͚ ެm͚оl:ڔ =t k       tMtWY+ښ5  Y+ښ5 } t )   <3  v _  g &   m͚ ެm͚оl:ڔ }t  zy  z  tMtWY+ښ5  Y+ښ5 } t )   <  ɛ  K  農V 5kF{ V 5kB   hS  Йf    ?  t]t_Y+ښ5  Y+ښ5 } t ) g L3u f /     +kE[ f 7kE[ & /  6e    x =ӵѝe hk֌ f hkք e ѦL  s   [ 왮  ,kE[ f 7kE[ & /  6e  k >    E_ӵѝe hk֌ f hkք e ѦL  s]Sots g >   m͚ ެm͚оl:ڔ ; l3u F7G/y  { Z ֬  Z ֬	 ˦ M    6Sotc    ޲V 5kF{ V 5kB   hS ]Sosc rg   .kE[ f 7kE[ & /  6e : L= ͍ ˝i   m͚ ެm͚оl:ڔ { |3  67F/w   V 5kF{ V 5kB   hS          k   .kE[ f 7kE[ & /  6e : 5u &7E/u 9   V 5kF{ V 5kB   hS  3      ԙ   Z ֬  Z ֬	 ˦ M    8S orS Rg   /kE[ f 7kE[ & /  6e .: L  
 
  9   V 5kF{ V 5kB   hS  3^ |   e 4
 a֊ f ho֊ fMh_6m  }tΙ  7D/s Y  V 5kF{ V 5kB   hS  s 4   !z 3 Bw    Y3ڛ   YڗMG 2} s    
 ˜i ìm͚ ެm͚оl:ڔ    4 7 z 3 C     Y3ڛ   YڗMG 2  : l  f % 4 c֊ f ho֊ fMh_6m t: L y    8 <t Y+ښ5  Y+ښ5 } t ) 1 3  
n ^ L  =f hk֌ f hkք e ѦLǠ  4 7 z  4 c֊ f ho֊ fMh_6m t: 5   m ^ L3 ]f hk֌ f hkք e ѦLǡ  4   zy3 Dw    Y3ڛ   YڗMG 2  ; \  F   4 e֊ f ho֊ fMh_6m t: Lsy{  7 Lt Y+ښ5  Y+ښ5 } t ) q 3   m ^ L3 ]f hk֌ f hkք e ѦLǡ ^ L  &  4 g֊ f ho֊ fMh_6m t,: L3ys   6 \t Y+ښ5  Y+ښ5 } t )ӱ  3   m ^ Ls }f hk֌ f hkք e ѦLǢ3 4 7 	zi3 E     Y3ڛ   YڗMG 2  < L  &  4 g֊ f ho֊ fMh_6m t,: L3ys   6 \t Y+ښ5  Y+ښ5 } t )ӱ  3   m ^ Ls }f hk֌ f hkք e ѦLǢ3_ <   e 4 i֊ f ho֊ fMh_6m t<: L xk  5 lt Y+ښ5  Y+ښ5 } t )    3  m ^ L ѝf hk֌ f hkք e ѦLǣs 4   zY3 Fw    Y3ڛ   YڗMG 2  = <   e 4 i֊ f ho֊ fMh_6m t<: L xk  5 lt Y+ښ5  Y+ښ5 } t )    3  m ^ L ѝf hk֌ f hkք e ѦLǣs 4   zY3 Fw    Y3ڛ   YڗMG 2  = <   e 4 i֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t:   , X9zI3 G     Y3ڛ   YڗMG 2     4 7V ^ L ѽf hk֌ f hkք e ѦL   + ⍕  4 |t Y+ښ5  Y+ښ5 } t ) y   J xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc  % 4 k֊ f ho֊ fMh_6m t: L xc 5 lt Y+ښ5  Y+ښ5 } t ) 9  3  m ^ L ѝf hk֌ f hkք e ѦLǣs 4   zY3 Fw    Y3ڛ   YڗMG 2  = <   e 4 i֊ f ho֊ fMh_6m t<: L xk  5 lt Y+ښ5  Y+ښ5 } t )    3  m ^ L ѝf hk֌ f hkք e ѦLǣs 4   zY3 Fw    Y3ڛ   YڗMG 2  = <   e 4 i֊ f ho֊ fMh_6m t<: L xk  5 lt Y+ښ5  Y+ښ5 } t )    3  m ^ Ls }f hk֌ f hkք e ѦLǢ3_ <  &  4 g֊ f ho֊ fMh_6m t,: L3ys   6 \t Y+ښ5  Y+ښ5 } t )ӱ  3   m ^ Ls }f hk֌ f hkք e ѦLǢ3 4 7 	zi3 E     Y3ڛ   YڗMG 2  < L  &  4 g֊ f ho֊ fMh_6m t,: L3ys   6 \t Y+ښ5  Y+ښ5 } t )ӱ  3   m ^ L3 ]f hk֌ f hkք e ѦLǡ ^ L  F   4 e֊ f ho֊ fMh_6m t: Lsy{  7 Lt Y+ښ5  Y+ښ5 } t ) q 3   m ^ L3 ]f hk֌ f hkք e ѦLǡ  4   zy3 Dw    Y3ڛ   YڗMG 2  ; \  F  ] <t Y+ښ5  Y+ښ5 } t ) 1  4   z 3 C     Y3ڛ   YڗMG 2  : l  f % 4 c֊ f ho֊ fMh_6m t: L y    8 <t Y+ښ5  Y+ښ5 } t ) 1 3  
n ^ L  =f hk֌ f hkք e ѦLǠ  4 7 z  4
 a֊ f ho֊ fMh_6m  }t k    șf ; Z ֬  Z ֬	 ˦ M    9 |   e 4
 a֊ f ho֊ fMh_6m  }tΙ  7D/s Y  V 5kF{ V 5kB   hS  s 4   !z  4  _֊ f ho֊ fMh_6m  ]t k  [  Й   Z ֬  Z ֬	 ˦ M    8S orS Rg   /kE[ f 7kE[ & /  6e .: L  M K i   m͚ ެm͚оl:ڔ  3u &7E/  f   Z ֬  Z ֬	 ˦ M    wM ɍы i   m͚ ެm͚оl:ڔ { |3  67F/w   V 5kF{ V 5kB   hS         ܙf   Z ֬  Z ֬	 ˦ M    7Sosc r    ޲V 5kF{ V 5kB   hS ]Soss g >   m͚ ެm͚оl:ڔ ; l3u F7G/y  { Z ֬  Z ֬	 ˦ M    6Sots     βV 5kF{ V 5kB   hS  ѹ   7*| 3] Y֊ f ho֊ fMh_6m  9: L} U ˞   βV 5kF{ V 5kB   hS  ѹf  
_ 5] W֊ f ho֊ fMh_6m  : 5  V   g .   m͚ ެm͚оl:ڔ 3t  :y  z 3] W֊ f ho֊ fMh_6m  : L  Y    k &   m͚ ެm͚оl:ڔ }t k       tMtWY+ښ5  Y+ښ5 } t )   <3  v _  g &   m͚ ެm͚оl:ڔ }t  zy  /z  t=tOY+ښ5  Y+ښ5 } t ) { ,     ?      =e hk֌ f hkք e ѦL\S/oW @ L C     Y3ڛ   YڗMG 2   2S7oX @ 5]
 Q֊ f ho֊ fMh_6m  :: 5u  / ! t-tGY+ښ5  Y+ښ5 } t )   3   / 1X u  d hk֌ f hkք e ѦL  s   [ֿ  `M A     Y3ڛ   YڗMG 2   pM  e!  d    m͚ ެm͚оl:ڔ 5t    M
 GaM @w    Y3ڛ   YڗMG 2=  oM{ u}2] M֊ f ho֊ fMh_6m  <: 5    M aX  ѽd hk֌ f hkք e ѦLϣ ˴o[7  aM G     Y3ڛ   YڗMG 2=  nM  u} 2  K֊ f ho֊ fMh_6m  : L{  u}$  [t'Y+ښ5  Y+ښ5 } t ) ctnkڋ7   C   N V 5kF{ V 5kB   hS    2  [ C X   }d hk֌ f hkք e ѦL љ i?޺  Ś~  #kE[ f 7kE[ & /  6e   lM     `  7 . V 5kF{ V 5kB   hS   ִ'o^O  ƚ~  "kE[ f 7kE[ & /  6e   kM{   4 p  |tY+ښ5  Y+ښ5 } t ) mt^     i  X    V 5kF{ V 5kB   hS&Fg  }y z	}@ t.   m͚ ެm͚оl:ڔ  YeڛO ^B 5    kE[ f 7kE[ & /  6e 7: 5  '@/ ɚ C矵  Y3ڛ   YڗMG 2  S&  e 1Y y   V 5kF{ V 5kB   hS  3Z |
     t Y+ښ5  Y+ښ5 } t ) ? e |     t Y+ښ5  Y+ښ5 } t )   |֤? $ m aY   ܳV 5kF{ V 5kB   hS ? ٬I i   㲦 ѹg hk֌ f hkք e ѦL  Y   Ӡ   fMǢ3 Z ֬  Z ֬	 ˦ M   I 'B  ̚ G 5  Y3ڛ   YڗMG 2=> ?  O >F 5  <kD; f 7kE[ & /  6e  3Y V> }l t,:  ̚ ެm    l2ړ  dMZ T +胳   yg hg֌ f hkֆ6f ўlgtk   W GgMǡ   ά  Z ֬
m & =   < $ⓡ  Ϛ Ag 5  Y3ڛ   YژMF{ ] Y I  t k  C  蜳F 3kF{ V 5kC  hO #: J ŧC_E 5} sֈvf ho֊ fmhc6  vD &     њ   8kD; f 7kE[ 6 1   d  3  {|B u !Z w g hg֌ f hkֆ6f ўl7tk #>%:}   =t Y#ڙ5  Y+ښ    d ' 	 _  ᓢC G  w  f hg֌ f hkֆ6f ўl' Mz O C 5}  mֆ6f hs֊ fmhc6  vA פg   0 q  9:׬
m    m    l2ړ vSҳ|Zt( @Q  iֆ6f hs֊ fmhc6  v@ פW   p Z g L 6 1kG  V 5kC  h _ v I     cE }t Yژ   Y+ښ    T %kG ) U>5:}   >:Ϭ
m    m    l*ڒ   k ;|rt p  }t Yڗ vg hgֆ6fSі  ]   ӣ  ǋ { , & /    ά
m̦ -Y+ JI   ѩ F ut Yڗ vg hgֆ6fSі m] >  S G     & /    ά
m\  vd h'%} 'H     f-h[ 
ڞ5  Y#ڙMD; 6   > S       e-h[ 
ڞ5  Y#ڙMD; 6 qM  $ } (=  /kA۲]       l"ڑ5 }  
>I   Qz ]ւ e   Y#ڙ5   D #kA ( [|  S  :    vA۳F 3kD; ihCւ Q 7 D   C     e
hW 
ڞ5  Y#ڙMC  mM 6 * } (=F MG          lڐ5 ]  m>U   Q   ,  6e;  Y#ڙ    $  g  &J: O . >| n  ʦ M Nhֈvf hk6	   d     ӥK    輲 hO ڟ5  Y+ښMA  d     ӥK    輲 h  Nhֈvf hk6   d      ˡ!%Fg ME[   d hg֊ fS ߞME[( h>e $  R 7:   hG :    Z ֵ	   &  t 4]})  S6
mX 
 Aֆ6f hsvu 7 MCn%  'M E [ 茲ihC #:  
m       o &  t 6]} )    $  g; s   Ƭm^ 2 { ih%  'N GJJ  Y      9dmhc֎6 ]   $  S  | 4}0)   g   o^  Eֆ6f;   U ߺ6   
>y >   Dg خ , 6 1  ^ " ; ) o   
>y >  ҟ l   Eֆ6f;  kWC   w J  > B [     < 6 1 m     |+ |5}Ho    wۄ e  퓻:  o%  O F    C   ^ оl' jWG3%] O Ƣ+   ?  dMh_  ?       §Q    ҟ l     dMh_ : I] ͔t%>  >   F s  謲& /  Ô    [IW    C{+ 	= Y  W;  rWG󭤫 T   JjA wւ ez   &   V  d }xo%5 g;kA 2 S \ J * NU     ZжL =S    'Tu C|+i2z   -  E ӭ   )U%   J     +  A ҭ 	|RU >̷    9k@ 2 U  J §U  }+i"z   + ^A Э I|bU >Է    8  6 IϢ  V 4>  } o%MB p6mʤg  s+i" \m >ܷ    7  6e 3 ٹ 4 O  B [Iг MG 2 znn%M   Ї ^ҕ 3 6 ɤ{虹 4 O  D {IWF l6 ɤ[ y    'Yۢ      5    I+zN %  i   /  Yͦ -     ^R hm >       l*ڒI   {Im|    >      ѵ hG&    {I |   C {IWB h6 Ȥ?гq/  O     + g3  6 I \ Kj .-    _  2  6d =     K7 ? {I D   $  g =  v  . A   % =    iO , KډO        + <fS ߞiO , KڍO     ( l  M@w   3 (iG> ғ ǣ   s ]  k      ]  K/     D `S        Ho &   @ ^S G  (I    F X%     ԍ  Q     }   <J:=w
    $  7B   y& H  MN 辟I ? VH_B t%        $1    3IG  mZ Dw (I   H_F   I:=sWO 讟I } % A ң$ }  I c )ҁ  3IR  =     H  T $I
   L ^ [#   i= $MD߳g    D  $i  =    I?@ ̞I    [ $ s Iҏ ? g  +  ԳI  &    3I     $} o t    $  { l   7K    l t     c vIC  M  Dߝg t, 2   I 7 w  $ ÷M 0   J  	        I ? W  W w $  7O  q  $=   $ 7|  a  +I   +I - Bi(   J    >   k m    &iO =x5I  )   &i       ͔  ? W ԉ  W t]  R! g j :   j   7U*E   M < .   |[ r O  $]   &i Zi O  $]
   &i& ^i3 O  $    &i6 biS O  $    w    Y    $IǠ  $u   O  $}  _ $  o    $ 5 }  n  n  $ >zo>I >| %=D?>Mҟ   4I  ͗ 4      { $  /   я o%    [I _I  J    o%Iɯ     L    o&Iį    " L zN  $= B a   Ig   $ Y~1$  ~  tzގH    C    QI   $ S~I$   92 z^ L  ɯ  K =g }  pF t . . ~    =  $ /  ˣIg 9   N   G (   w >~ $  _!Ic      J t~ $ՠ]WM  j tU~ $բe j@ &%IS Œ 
  f I T~ $m ~  ^IR
 h 臟u$I   I  Ѯ $  / $  ~LڹI   Q   ~| gI   K)I'   'I  _RI (  ;-I 9  J $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I   G $I 4 ? %I    Q/I $
 zI $i8 K $I   ^ $I   $I p   $I F    4 ^R      IEND B` 
--03f4a88b-95cb-4ce5-a097-6874f30d473e--

**Comment by csillagd** [comment]
Nekem ugyanez a problémám, hogy állandóan FILE_TYPE_MISMATCH-ot kapok, pedig a fájlnév mezőben benne hagyom a kiterjesztést. Ennél a requestnél szükséges a fájlt tömöríteni? Ha tömörítem, ha nem, ugyanezt a hibát kapom.
Van esetleg egyéb vizsgálati szempont, ami alapján elhasal a requestem?

Csatoltam a Fiddler által logolt nyers requestem. Az octet-stream rész elejéből látszik, hogy még a Fiddler is PNG-nek nézi.
Köszönöm a segítséget!
![image](https://github.com/user-attachments/assets/c080a380-7031-4430-82af-0b7b8ebe5ed7)


[1259_Request.txt](https://github.com/user-attachments/files/17657656/1259_Request.txt)

**Comment by renced42** [comment]
Szia!

A requestben a Content-Type: application/octet-stream. 
A speciben viszont ez van:

A manageDeclarationPartition és a manageAttachmentUpload esetén a megadandó content-type:
● content-type = multipart/form-data

ezt érdemes megnézni.

**Comment by csillagd** [comment]
Kedves @renced42 !

A manageAttachmentUpload "burkoló request" content-type az multipart/form-data. A benne lévő xml content az application/xml és csak maga a fájl content az, aminek a típusa application/octet-stream. Ez a beágyazás a manageDeclarationPartition-nál működött. 
Tehát a teljes requesthez tartozó content-type az multipart/form-data és benne van egy application/xml és egy application/octet-stream.
Ha a fájl contentet átállítom multipart/form-data típusra, akkor a szerver nem találja az xml névteret.
![image](https://github.com/user-attachments/assets/0efd562d-e280-43af-a799-d0e27e33bcbb)

**Comment by renced42** [comment]
Kedves @csillagd 

Kérlek, hogy a Content-Dispositiont egészítsd ki valahogy így

Content-Disposition: form-data; name="file"; filename="Névtelen.png"

**Comment by csillagd** [comment]
Köszönöm, így megoldódott! 🫡
