### ISSUE TITLE
Áfaanalitika véglegesítése után több napja PROCESSING állapotban maradt a feldolgozás

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/eVAT#68]
A manageDeclarationFinalize futtatása után már több mint 3 napja PROCESSING declarationStatus-ban maradt a beküldött analitikánk az eÁFA teszt rendszerben.
Miért nem került feldolgozásra?
A kérdéses declarationUploadId-k: 4FM9I5RALIPBW31M, 4FMCLPU7Z5OD6OWM.

A teszt rendszerbe hogyan lehet nyugtákat, valamint vámhatározatokat beküldeni tesztelés céljából?

**Comment by szako** [comment]
Nálunk is PROCESSING státuszban vannak a feltöltött bevallások, szóval nem egyedi eset.

**Comment by szako** [comment]
@renced42: Megint PROCESSING státuszban van(nak) a beküldött bevallás(ok). Mikori gyakoriságú a frissítés? Mire készüljek a teszt rendszeren?

UploadID: 4FTBC119YCLYMLXT, 4FTBF2HD88PG8YY2
Process ID: 4FTBC1TPNBEGP0XV, 4FTBF34OJE0ZTLY4

Köszönöm!

**Comment by renced42** [comment]
Kedves @szako 

Vizsgáljuk a problémát. Itt nincs olyan, hogy frissítés, ennek folyamatában kell mennie pikk-pakk.

**Comment by balintdozsa** [comment]
A probléma továbbra is fennáll, jelenleg a kettes és hármas verziójú analitika áll PROCESSING-ben.

1: 4FM9I5RALIPBW31M,
2: 4FMCLPU7Z5OD6OWM,
3: 4G0K9ZHPOB7OTN1F

**Comment by balintdozsa** [comment]
Most már úgy tűnik a feldolgozás működik, azonban itt nem teljesen világos hogy mi a baj (declarationProcessingId: 4G24NTMTMVCQWP1Q):

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:QueryDeclarationProcessingStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/EAR/1.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns4="http://schemas.nav.gov.hu/EAR/1.0/data" xmlns:ns5="http://schemas.nav.gov.hu/EAR/1.0/base" xmlns:ns6="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns7="http://schemas.nav.gov.hu/OSA/3.0/data"><header><requestId>RID085350200170541394356210</requestId><timestamp>2024-01-16T14:05:43.854Z</timestamp><requestVersion>1.0</requestVersion><headerVersion>1.0</headerVersion></header><result><funcCode>OK</funcCode></result><ns2:declarationProcessingStatus><ns2:declarationInfo><ns5:modificationReference/><ns5:taxNumber>12715244</ns5:taxNumber><ns5:declarationType>NONE</ns5:declarationType><ns5:declarationKind>NONE</ns5:declarationKind><ns5:declarationFrequency>MONTHLY</ns5:declarationFrequency><ns5:declarationPeriodStart>2023-06-01</ns5:declarationPeriodStart><ns5:declarationPeriodEnd>2023-06-30</ns5:declarationPeriodEnd><ns5:version>4</ns5:version></ns2:declarationInfo><ns2:declarationStatus>FINISHED</ns2:declarationStatus><ns2:businessValidationMessages><ns2:validationResultCode>WARN</ns2:validationResultCode><ns2:validationErrorCode>t000</ns2:validationErrorCode><ns2:message>Figyelem! Valódi ellenőrzés folyamat nem futott (külső warning)!</ns2:message></ns2:businessValidationMessages><ns2:declarationUploadId>4G24N6AESR7ETS1O</ns2:declarationUploadId><ns2:contentHash cryptoType="SHA3-512">08677ACC98D488AB6AF634C5B166BE1E03CFC8AF92D0258F4B3C9D41D2E7A101DB68C1351F230DEC2DEB1534CC653E96D9E7EB7B073F1EDF8A150D726FB2C656</ns2:contentHash><ns2:declarationSchema>VAT_DECLARATION</ns2:declarationSchema><ns2:originalRequestVersion>1.0</ns2:originalRequestVersion></ns2:declarationProcessingStatus></ns2:QueryDeclarationProcessingStatusResponse>`

**Comment by renced42** [comment]
@balintdozsa 
Ezt hol küldted be?

**Comment by balintdozsa** [comment]
@renced42 
A teszt rendszerben, a manageDeclaration funkciókkal lett feltöltve az analitika.

**Comment by renced42** [comment]
Kedves @balintdozsa 

Ez a probléma elvileg megszűnt, ha mégis előfordul nyisd újra kérlek.
