### ISSUE TITLE
NAV kódok használata

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#70]
El kellene dönteni végre, hogy mi is az adókód, mit kell használni. Jelenleg én hatalmas keveredést látok az eÁFA teszt rendszer Webes felületén, és a korábban közzétett információk között:
Beállítások menü/Szabályok fül/Új szabály létrehozása/Típus: "Adókód" hozzárendelése   - még az sem tisztázott, hogy melyik adókódról van szó: Standard, vagy Beszédes adókódról.
Majd a feltételek megadása után a Műveleteknél megjelenik az „Adókód” mező. Kérdésem: melyiket jelenti a jelző nélküli adókód? Belekattintva ilyen van benne: „F07 38” ebből gondolom azt, hogy ez bizony nem a Standard adókód.
Másik hely a Webes felületen: Bizonylatlista menüben a tételsoron állva, majd kiválasztva a „Számla adatok, adókód megtekintése”-t, megint „Adókód” szöveg látható a fejlécben, és L66  van benne, ami megintcsak nem a Standard adókód, hanem a másik. 
Harmadik hely: Bizonylatlista menü/ Kimutatások/Levonandó adókód szerinti kimutatás: Ebben megint jelző nélküli „Adókód” kifejezés szerepel, benne megintcsak nem a Standard adókód szerepel, hanem a „Beszédes adókód”.
Ameddig a fogalmak nem egyértelműek, addig félreértések lesznek.
1.	kérdés: Minek van a Standard adókód, és egyáltalán mi a célja a kétfajta kódolásnak?
2.	kérdés: Melyiket kell használni a M2M kapcsolat esetén?
3.	kérdés: Előfordulhat az, hogy M2M kapcsolat esetén a Standard adókódokat kell használni, de a Webes felületen a Beszédes kódokat (ami semmivel nem beszédesebb, mint a Standard adókód)?

**Comment by renced42** [comment]
Kedves @Macskafarka 

Köszi az észrevételeket :)

Röviden megválaszolom a kérdéseidet:

1.) kérdés: Minek van a Standard adókód, és egyáltalán mi a célja a kétfajta kódolásnak?
A standard adókód egy hosszabb, angol nyelvezetből levezetett betűk - és a bevallás soraihoz kapcsolódó - tetszőleges, de algoritmizált módon összeállított mezőkombinációk halmaza.
A "Beszédes adókód" vagy inkább  "Egyszerűsített adókód" a standard adókódnak egy az egybeni megfeleltetése, ami rövidebb könnyebben megjegyezhető.  Ezzel a kóddal kizárólag a webes felületen lehet találkozni a különböző listákban.


2.) kérdés: Melyiket kell használni a M2M kapcsolat esetén?
A standard adókódot

3.) kérdés: Előfordulhat az, hogy M2M kapcsolat esetén a Standard adókódokat kell használni, de a Webes felületen a Beszédes kódokat (ami semmivel nem beszédesebb, mint a Standard adókód)?
A felületen a kiválasztott adókód mögött valójában a standard adókód áll.
A standard adókód egy egyedi id ami definiálja, hogy a bevallás melyik mezőjébe kerül az adott tételhez tartozó összeg A Beszédes adókód ennek a címkéje ami a felületen megjelenik.

Persze azon lehet lamentálni, hogy a beszédes adókód mennyire beszédes, sok mindenkit megkérdeztünk ezzel kapcsolatban. Szoftverházakat könyvelőket is. Ennek elnevezése nincs kőbe vésve most így néz ki. Természetesen az ügyféli igényeket is figyelembe vesszük.

**Comment by omachtandras** [comment]
"Ennek elnevezése nincs kőbe vésve most így néz ki. Természetesen az ügyféli igényeket is figyelembe vesszük."

Annyi kérés lenne, hogy ha már bevezetésre került ez a Beszédes kód és ez látható a NAV felületén, akkor ne legyen megváltoztatva a későbbiekben. Nem látom a hozzáadott értékét a standard kódokhoz képest, de úgy gondolom, hogy ha a NAV felületén ez fog látszani, akkor a fejlesztők kénytelenek lesznek a saját felületeiken is ezt használni, ha nem akarják állandóan azt magyarázni az egyezőségre vágyó ügyfeleknek (könyvelők), hogy miért nem azt látják itt, amit a NAVnál ott...
Ha viszont ezeket szokják meg, akkor egy változtatás nem esne jól senkinek...
