### ISSUE TITLE
REQUEST_ID_NOT_UNIQUE /queryTaxCodeCatalog esetén

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/eVAT#71]
Sziasztok!

A hívások pár százalékánál /queryTaxCodeCatalog esetén REQUEST_ID_NOT_UNIQUE hibaüzenetet kapunk a NAV teszt rendszeréből, ami elvileg nálunk nem lehetséges, eddig a sok év során nem volt ilyen problémánk. Ilyen requestId-k:

```
<requestId>24011013lRHfnLQv7jwhzdDkq1w0rm</requestId>
<timestamp>2024-01-10T12:27:26Z</timestamp>

<requestId>24011013lRHfnLQv7jwhzdHGtJhWrm</requestId>
<timestamp>2024-01-10T12:27:36Z</timestamp>

<requestId>24011013lRHfnLQv7jwhzdT5ry+Wrm</requestId>
<timestamp>2024-01-10T12:28:16Z</timestamp>

<requestId>24011013lRHfnLQv7jwhzdX3ASZ0rm</requestId>
<timestamp>2024-01-10T12:28:30Z</timestamp>

<requestId>24011013lRHfnLQv7jwhze3WrEM0rm</requestId>
<timestamp>2024-01-10T12:30:26Z</timestamp>

<requestId>24011110lRHfnLQv7jwiZ1mq9NA0rm</requestId>
<timestamp>2024-01-11T09:07:50Z</timestamp>

```

Az összes többi esetben nincs hiba. Meg tudnátok nézni, hogy a ti oldalatokról mit láttok? Mi a másik requestId tartalma, amire duplikációt ír?

Köszönöm!

**Comment by EPluribusUnum** [comment]
Online számla esetén volt ilyen, ott nem volt érdemben előrejutás.

https://github.com/nav-gov-hu/Online-Invoice/issues/870

**Comment by renced42** [comment]
Köszi a jelzést!
Meg van a probléma egy paramétert fogunk állítani.

**Comment by EPluribusUnum** [comment]
@renced42 , a paraméter állítás csak az eVAT-ra vonatkozik, vagy az Online-Invoice-ra is?

**Comment by renced42** [comment]
Kedves @EPluribusUnum , @szako 
Elvileg a kollégák beállították, tehát nem kellen már a hibának előfordulnia.
