### ISSUE TITLE
Közösségi számlák eÁFA-ban

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#72]
Tervbe van-e véve, hogy a Közösségi számlák is elérhetők lesznek M2M kapcsolattal? Tudom, hogy az aktuális bevalláskor még nem áll a NAV rendelkezésére info, a kérdés arra vonatkozik, hogy miután a NAV megkapja a társországok adószerveitől, akkor elérhetővé válnak-e.

**Comment by renced42** [comment]
Kedves @Macskafarka 
Látom sok szakmai kérdést tettél fel most.
Kérlek, hogy a szakmai kérdéseket kérlek a Discussion-ban tedd fel.

Köszönöm szépen!
