### ISSUE TITLE
M2M bevallás koncepció

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#74]
Mikor lesz végleges M2M "Áfabevallás releváns gép-gép kapcsolat koncepció"? A jelenleg elérhető legfisebb leíráson a "Tervezet" szerepel.

**Comment by renced42** [comment]
Kedves @Macskafarka 

A tervezet a specifikáció kiadásával kvázi végleges lett. A megjelent specifikáció az irányadó a fejlesztésben.

**Comment by Macskafarka** [comment]
Tehát ez lett a végleges: "A könyvelőprogramok és az adóhivatal eÁFA webes felületén kialakított szabályok átjárhatóságát **jelentősen támogatná** az ügyféli szabályok API-n keresztüli feltöltése és letöltése."  Meg ez: "Az M2M bevallás XML-ből leképezhető a jelenlegi 65-ös nyomtatvány teljes adattartalma. A könyvelők számára **jelentős hozzáadott értéket jelentene**, ha az M2M bevallást a hagyományos űrlap szerkezetben is meg tudná nézni."   - A feltételes mód helyett én konkrétumokat vártam. Tehát valami vagy működik vagy nem. Az kevés, hogy "jó lenne", meg "támogatná".

**Comment by renced42** [comment]
Kedves @Macskafarka 

A tervezet két éve készült. Amikor még ez íródott még nyilván egy felmérési szakaszban volt a dolog, tehát jogos, hogy abban feltételesen fogalmaztak.
Ami a specifikációban megjelent az valósult meg egyenlőre a tervezetből, de a szolgáltatások folyamatosan bővülni fognak.

Aktuális specifikáció: [docs/spec/eÁFA_M2M_rendszer_interfesz_specifikacio_v0.5.pdf](url)
