### ISSUE TITLE
Hibás adókódok?

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/eVAT#75]
Sziasztok,

lehet, hogy nem hiba, de nekem nagyon úgy tűnik, ezért inkább rákérdezek...
docs/standard_adokod/TAX_CODE_CATALOG_20231026.xlsx

Úgy tűnik, mintha a mezőgazdasági és a vas fel lenne cserélve minden VV és VM végű kódnál.
Pl.:
MP29 DP101 MD66 PG08 V**_M_**
"Az Áfa tv. 6/B. sz. mellékletében szereplő **_vas és acél termékek_** beszerzése után fizetendő 27%-os mértékű adó, adólevonással, melléklapon szereplő nyilatkozattétellel"

MP29 DP101 MD66 PG08 V**_V_**
Az Áfa tv. 6/A. sz. mellékletében szereplő **_mezőgazdasági termékek_** beszerzése után fizetendő 27%-os mértékű adó, adólevonással, melléklapon szereplő nyilatkozattétellel

Nem az M akarja jelölni a mezőgazdasági termékeket és a V a vas és acélt?

**Comment by renced42** [comment]
Kedves @omachtandras 

Igen ez egy hiba. Most került ki az új módosított adókód katalógus.

**Comment by omachtandras** [comment]
Köszönjük. Nem tudom, hogy lehet-e olyat kérni, hogy a kezdetekben publikált "sokoszlopos" változat is kikerülhetne, nem csak ez a három oszlopos. Ott szépen lekövethető volt, hogy milyen kód milyen ányk sort/lapot vezérel. Ha véletlenül a logika (is) változik, akkor ez nagy segítség a fejlesztőknek, nem kell a kódokból kitalálni, hogy mit-hová kellene tenni. A sorokat egyszerű(bb) persze, de pld. pont a mezőgazdasági és vas az, ami már egyedi logika, és a jövőben is bármikor jöhet egy újabb "lap", ami újfajta kódrészt, megjelenését, töltési logikát eredményezhet. Ilyenkor egyből látható lenne, hogy a NAV mire is gondol, hogy kell dekódolni.

**Comment by renced42** [comment]
Kedves @omachtandras 
Erre gondolsz?

[TAX_CODE_CATALOG_20240113_extended.xlsx](https://github.com/nav-gov-hu/eVAT/files/13930870/TAX_CODE_CATALOG_20240113_extended.xlsx)

**Comment by omachtandras** [comment]
> Kedves @omachtandras Erre gondolsz?
> 
> [TAX_CODE_CATALOG_20240113_extended.xlsx](https://github.com/nav-gov-hu/eVAT/files/13930870/TAX_CODE_CATALOG_20240113_extended.xlsx)

Oh, igen, elkerülte valahogy a figyelmem, KÖSZÖNÖM!

**Comment by renced42** [comment]
Nem csak még nincs kint.
