### ISSUE TITLE
xx60 Közösségi Összesítő nyilatkozat

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#76]
Kiváltja-e az eÁFA bevallás az xxA60 Közösségi Összesítő jelentést?
Ha igen, akkor kaphatnánk segítséget arra vonatkozóan, hogy az 1-4 lapokhoz mely Standard adókódok tartoznak?

**Comment by renced42** [comment]
Kedves @Macskafarka 
Kérelk a kérdést a Discussionban tedd fel.

Köszönöm szépen!
