### ISSUE TITLE
KL V00 /L00 használata

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/eVAT#77]
1. Ha a számlabefogadó nem akar levonási jogot gyakorolni egy adott tételsor után, akkor helyes-e, ha egyszerűen nem szerepelteti a eÁFA bevallásban, vagy elvárás az, hogy lássa el valamilyen adókóddal, pl. KL V00-lal?
2. Keletkezik-e ilyen esetben validációs üzenet, ha igen, akkor ERROR, vagy WARNING?
3. Ha komplett számla után nem érvényesítenek levonási jogot, hanem egyszerűen nem szerepeltetik az áfa bevallásban, akkor arra van-e ERROR, vagy WARN?

**Comment by Macskafarka** [comment]
Életszerű példa: ha a számlabefogadó az áfa bevallásig nem tudott meggyőződni arról, hogy fennáll-e a levonási joga az adott bizonylaton szereplő áthárított adót illetően, hanem még utána akar járni a gazdasági eseménynek.

**Comment by Macskafarka** [comment]
Tetszik a tervezett warning, ami a bizonyalt egészére vonatkozik. . Az 1. kérdésem arra vonatkozott, hogyha a számlán belül lesz olyan tételsor, amelyet adókóddal látunk el az eÁFA-ban, és mellette lesz olyan tételsor is, amit nem látunk el adókóddal M2M bevallás esetén. Ennek oka, hogy  úgy gondoljuk, hogy nem nyilatkozunk róla, elég az, ha azokról a tételsorokról nyilatkozunk, amelyre adólevonási jogot alapozunk számlabefogadóként.

**Comment by Macskafarka** [comment]
Kedves @renced42, Ezt írtad: "De ha egy bizonylat az adott időszakba esik akkor mindenképpen valamilyen adókóddal kell ellátni."   Ez így általánosan problémás lehet, mivel vannak olyan eseteke, amikor pusztán a számla alapján nem lehet megállapítani azt, hogy melyik áfa időszakban kell bevallani. Példa erre a pénzforgalmi áfa esete, amely mind a számlakiállítónál, mind a számla befogadónál a pénzügyi rendezéskor válik bevallhatóvá. Ha csak a számla befogadó pénzforgalmi áfás, akkor ráadásul más napon válik a számlakiállítónál fizetendővé, és más napon válik a számla befogadónál levonhatóvá. A más napok eredményezhetnek akár más áfa időszakot is.  A másik ellenvetésem arra az esetre vonatkozik, hogy az áfa törvény alapján  két éven belül bármikor gyakorolhatom befogadott számla alapján az áfa levonási jogot a tárgyhavi áfa bevallásban, ehhez nem kell önrevíziózni. Tehát, ha a NAV a 2024.01. havi bevallásban gondolja levonásba helyezni (mert ez a teljesítési dátuma) , attól még én számlabefogadóként megtehetem azt, hogy csak 2025.06. havi eÁFA bevallásba teszem be, azaz 18 bevallási időszakkal később.

**Comment by renced42** [comment]
Bocs lehet félreérthetően fogalmaztam. Szóval a webes felületen minden számlához tartozó tételt adókódolni kell.
Azokról is döntést kell hozni, amik nem az adott bevallási időszakba kerülnek majd az adózó döntése alapján. Ezek a számlák illetve tételei a munkakosárba kerülnek ahonnan később majd fel lehet őket használni. Ezt a felület kezelni tudja van rá lehetőség.

Munkakosárba kerül a bizonylat, ha:
●	 a felhasználó elhalasztotta, vagy
●	a felhasználó részben elhalasztotta, vagy
●	pénzforgalmi elszámolással érintett, vagy
●	másik időszakba tartozik, vagy
●	köztes elem annulálása miatt visszavonták, vagy
●	időszakon kívüli teljesítési dátum módosítással érintett, vagy
●	bevallásból kézzel/szabállyal kivett, vagy
●	másik időszakba tartozó alapszámlát módosító, érvénytelenítő számla.

A gépi interfészen beküldendő analitikában a NAV nem feltétlenül kéri be a számla összes tételét, hiszen nem feltétlenül rögzítik a könyvelő programokban a számlák tételsorait. (Persze lehet ilyen). Általában összesítve rögzítik azt. Pl ugyanolyan adókód alá tartozó 23 sort 1 sorban rögzítik összesítve. 
Az áfa analitikában a megadott adatok alapján ezeket az összefüggéseket az eÁFA rendszer tudni fogja és vizsgálja is majd.

**Comment by renced42** [comment]
Kedves @Macskafarka 

Ezt az Issuet lezárom, további szakmai kérdést ami nem hiba azt a Discussionban tedd fel.
Köszönöm szépen!
