### ISSUE TITLE
FORBIDDEN

### ISSUE THREAD

**Issue by clapygeza** [nav-gov-hu/eVAT#90]
Sziasztok!
Első eÁfa lekérésem egy queryTaxCodeCatalog lenne, de mind a teszten, mind az élesen kirúg azzal, hogy jogosultság szükséges. A technikai felhasználónál bepipáltam az eÁfa elérést teszten is és élesen is. Valahol kell még valamit állítani?  Köszi

**Comment by vbela75x** [comment]
Végre valaki más is jár, Ugyan ez a bajom nekem is. Mind a teszt mind az élesben ugyanez a hibám a felhasználóknak be van állítva az eÁFA joga. Kíváncsi vagyok a megoldásra. :)  A számla és OPF adatok lekérdezése tökéletesen megy az válaszban nem jelzi az xml-t hibásnak hanem csak FORBIDDEN a válasz.

**Comment by szako** [comment]
Az eÁFA webfelületén is engedélyezni kell a funkciókat: Felhasználók menüpont, ha jól emlékszem.

**Comment by vbela75x** [comment]
@szako köszi meglett már megy is.

eÁFA felület Felhasználók/Technikai fül  3 pötty itt kell

**Comment by ppsofthu** [comment]
Sajnos az én problémámat nem oldja meg. Nekem nem jelennek meg a másodlagos felhasználók az e-ÁFA ban a megjelölt helyen.    Az e-ÁFA interfész elérés be van jelölve az onlineszámlában.

**Comment by clapygeza** [comment]
Az onlineszamlaban bejelölöd a technikai felhaszálónál az e-Áfa elérést. Utána a eafa-test.nav.gov.hu - n belépsz elsődlegessel, majd felhasználók, technikai, a technikai felhasználó sorában a három pötty, szerkesztés és mindhármat pipáld be
