### ISSUE TITLE
xml példák

### ISSUE THREAD

**Issue by PongraczIstvan** [nav-gov-hu/eVAT#94]
Az XML  példák még fognak bővülni a végpontok lekérdezésével kapcsolatban?

**Comment by renced42** [comment]
Kedves @PongraczIstvan 
Egyenlőre nem de ha van valamire igény azt jelezd kérlek.

**Comment by PongraczIstvan** [comment]
A /manageDeclarationUpload és /manageDeclarationPartition példák sokat segítenének... Előre is köszi! :)

**Comment by u319169** [comment]
Kedves PongraczIstvan!
Példa xml-ek helyett inkább mellékelek egy Postman api-csomagot, amit beimportálva, az összes funkció tesztelhetővé válik, valamint a küldött és fogadott XML-ek láthatók lesznek.
[vdrapi - Demo.postman_collection_v2.json](https://github.com/user-attachments/files/17897638/vdrapi.-.Demo.postman_collection_v2.json)

**Comment by PongraczIstvan** [comment]
Köszönöm! :)
