### ISSUE TITLE
TaxPointDate, SourceDocumentType ?

### ISSUE THREAD

**Issue by tothj74** [nav-gov-hu/eVAT#95]
Az eÁfa teszt rendszerbe feltöltött dataXML-t feltöltés előtt minden alkalommal séma validációnak vetem alá. 
A sikeres validációt követően felküldött dataXML-t-re a queryDeclarationProcessingStatus végpontot ezt az üzenetet kapom:

**Invalid XML séma!\ncvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/EAR/1.0/data":taxpointDate}'. One of '{"http://schemas.nav.gov.hu/EAR/1.0/data":sourceDocumentType}' is expected.**

Természetesen a TaxpointDate minden sorra ki van töltve, a SourceDocumentType pedig nem kötelezően kitöltendő a séma szerint.

**Comment by EPluribusUnum** [comment]
@tothj74 , akkor namespace probléma lesz ott.

**Comment by renced42** [comment]
Kedves @tothj74 

Most települt ki egy új verzió és az XSD változott.
A repo updatelve lett ahol a sourceDocumentType már kötelező.

**Comment by tothj74** [comment]
@renced42 köszönöm. Legalább kiderült, hogy miért lett hirtelen hibás, ami előtte már működött.
