### ISSUE TITLE
application.wadl kérdések/kérések

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/eVAT#96]
1: mediaType bizots helyes?
/manageAttachmentUpload és /manageDeclarationPartition esetén multipart/form-data a request mediaType és nem application/xml vagy text/xml

2: resource path összevonás
A resource path="/analyticsService/v1" többször szerepel. Megoldható hogy egy tag alatt szerepeljen az összes method?

Köszönöm.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
1.) igen ez így jó
2.) Bár a jelenlegi is szabványos, de módosították a kollégák. 
Fel is töltöttem a friss verziót.
