### ISSUE TITLE
Webes felület előellenőrzés eredménye

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/eVAT#99]
A tesztrendszerben és az éles rendszerben is azt tapasztalom, hogy januári bevallástervezet elkészítése után a webes felületen az előellenőrzés eredményénél megakad, és körülbelül 5 napja már ott áll és nincs eredmény (nem sok számlával rendelkező adózó).

Mi lehet ennek az oka?
![image](https://github.com/nav-gov-hu/eVAT/assets/31219083/b49a6ad3-252e-4810-b168-52c1985659f3)

**Comment by tothj74** [comment]
@bmatyi94 nekem az éles rendszerben most a ManageDeclarationUploadRequestre is ez jön:
<result>
<funcCode>ERROR</funcCode>
<errorCode>OPERATION_FAILED</errorCode>
<message>Technikai hiba! Kérjük, próbálkozzon később!</message>
</result>

**Comment by renced42** [comment]
Kedves @bmatyi94 

Elvileg nem kellene már ilyen hibát kapnod. Lezárom az Issuet. Ha mégis probléma van az előellenőrzéskor, nyisd újra.
